### < 팀 만들기 >

- teams.csv 를 읽어들여서 DataFrame 으로 만듭니다.
- 28명을 4명씩 짝을 지어서 팀을 구성합니다.
- 총 7팀을 랜덤하게 배정합니다.

- 'team'이라는 이름의 Column을 하나 추가합니다.
- int형으로 해당하는 팀의 숫자값을 저장합니다.
- team_result.csv 파일로 결과를 저장합니다.

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [35]:
teams_df = pd.read_csv('datas/teams.csv')
teams_df

     성명 성별
0   강예림  여
1   강호정  남
2   고유리  여
3   김정인  여
4   김지성  남
5   김지오  여
6   노재승  남
7   박기영  남
8   박수현  여
9   배선화  여
10  서덕원  남
11  유승현  남
12  유영은  여
13  유예빈  여
14  유준선  남
15  윤영주  여
16  이유단  여
17  이윤진  여
18  이주현  여
19  이주현  남
20  임혜신  여
21  장서현  여
22  정현호  남
23  조세연  남
24  조재희  남
25  채경민  남
26  최진명  남
27  한혜원  여

In [56]:
teams_df['team'] = 0
teams_df

     성명 성별  team
0   강예림  여     0
1   강호정  남     0
2   고유리  여     0
3   김정인  여     0
4   김지성  남     0
5   김지오  여     0
6   노재승  남     0
7   박기영  남     0
8   박수현  여     0
9   배선화  여     0
10  서덕원  남     0
11  유승현  남     0
12  유영은  여     0
13  유예빈  여     0
14  유준선  남     0
15  윤영주  여     0
16  이유단  여     0
17  이윤진  여     0
18  이주현  여     0
19  이주현  남     0
20  임혜신  여     0
21  장서현  여     0
22  정현호  남     0
23  조세연  남     0
24  조재희  남     0
25  채경민  남     0
26  최진명  남     0
27  한혜원  여     0

In [73]:
names = list(teams_df['성명'])

np.random.shuffle(names)

teams_df['성명'] = names

teams = [names[i:i+4] for i in range(0, len(names), 4)]

teams

[['채경민', '김지성', '배선화', '서덕원'],
 ['김지오', '박기영', '정현호', '임혜신'],
 ['고유리', '유예빈', '강호정', '이윤진'],
 ['이주현', '장서현', '최진명', '유승현'],
 ['조세연', '유영은', '박수현', '한혜원'],
 ['조재희', '이유단', '노재승', '윤영주'],
 ['유준선', '강예림', '김정인', '이주현']]

In [75]:
# 기영
teams = pd.read_csv('datas/teams.csv')
o = list(range(1, 8))*4
np.random.shuffle(o)
teams['team'] = o
teams = teams.sort_values('team')
for i in range(teams.team.max()):
    temp = teams.loc[teams.team==(i+1)]['성명']
    print(f'{i+1}팀: ',list(temp))

1팀:  ['채경민', '윤영주', '유준선', '유영은']
2팀:  ['한혜원', '이주현', '김지오', '최진명']
3팀:  ['정현호', '장서현', '유예빈', '고유리']
4팀:  ['김지성', '조재희', '박기영', '서덕원']
5팀:  ['강호정', '조세연', '유승현', '이윤진']
6팀:  ['임혜신', '김정인', '노재승', '이주현']
7팀:  ['이유단', '박수현', '배선화', '강예림']

In [76]:
# 서현
df = pd.read_csv('C:/python/datas/teams.csv')
team = df.sample(28)
team['team'] = [_ for _ in range(1, 8) for i in range(1, 5)]
team.to_csv('team_result.csv', index=False)
pd.read_csv('team_result.csv')

     성명 성별  team
0   박기영  남     1
1   이주현  남     1
2   채경민  남     1
3   강호정  남     1
4   장서현  여     2
5   배선화  여     2
6   유준선  남     2
7   이유단  여     2
8   김정인  여     3
9   최진명  남     3
10  정현호  남     3
11  유예빈  여     3
12  고유리  여     4
13  윤영주  여     4
14  김지오  여     4
15  김지성  남     4
16  이윤진  여     5
17  강예림  여     5
18  조재희  남     5
19  유영은  여     5
20  서덕원  남     6
21  임혜신  여     6
22  유승현  남     6
23  이주현  여     6
24  한혜원  여     7
25  박수현  여     7
26  노재승  남     7
27  조세연  남     7

In [3]:
# 지성님

# 팀짜기 코드 (어제 발표이외 다른 코드)
df = pd.read_csv('teams.csv')
df['team']=np.random.choice(range(1,len(df)+1),size=len(df),replace=False)%7+1
display(df.sort_values('team'))

FileNotFoundError: [Errno 2] No such file or directory: 'teams.csv'

In [ ]:
# teams.csv 파일을 읽어들인다.
teams_df = pd.read_csv('datas/teams.csv')

# names 리스트에 모든 이름을 저장한다.
names = list(teams_df['성명'])

# random 모듈의 shuffle 함수를 이용하여 names 리스트를 랜덤하게 섞는다.
random.shuffle(names)

# 4명씩 묶어서 teams 리스트에 저장한다.
teams = [names[i:i+4] for i in range(0, len(names), 4)]

In [ ]:
# 결과 출력
for i, team in enumerate(teams):
    print(f"Team {i+1}: {team}")